version: 2

models:
  - name: fct_orders
    description: "Fact table for Amazon orders"
    columns:
      - name: order_date
        tests: [not_null]
      - name: revenue
        tests: [not_null]
      - name: sku
        tests: [not_null]

  - name: fct_ads
    description: "Fact table for Amazon ad spend"
    columns:
      - name: ad_date
        tests: [not_null]
      - name: ad_spend
        tests: [not_null]
      - name: sku
        tests: [not_null]

  - name: fct_inventory
    description: "Fact table for inventory stock"
    columns:
      - name: snapshot_date
        tests: [not_null]
      - name: sku
        tests: [not_null]
      - name: afn_fulfillable_quantity
        tests: [not_null]

  - name: mrt_kpi_daily
    description: "Marketing + Inventory KPIs by date and SKU"
    columns:
      - name: date
        tests: [not_null]
      - name: sku
        tests: [not_null]
      - name: revenue
        tests: [not_null]
      - name: ad_spend
        tests: [not_null]
      - name: tacos
        tests: [not_null]
      - name: stock
        tests: [not_null]
      - name: days_of_cover
        tests: [not_null]
